module.exports = [
  {
    email: null,
    first_name: 'Melvin',
    last_name: 'Staats',
    middle_name: null,
    notes: 'Newton commons, wife Myrna',
    suffix: null,
  },
  {
    email: null,
    first_name: 'Myrna',
    last_name: 'Staats',
    middle_name: null,
    notes: 'Newton commons, husband Melvin',
    suffix: null,
  },
  {
    email: null,
    first_name: 'Georgia',
    last_name: 'Raeburn',
    middle_name: null,
    notes: 'Newton commons',
    suffix: null,
  },
  {
    email: null,
    first_name: 'Mona',
    last_name: 'Dockry',
    middle_name: 'Flash',
    notes: null,
    suffix: null,
  },
  {
    email: null,
    first_name: 'Saoirse',
    last_name: 'Dockry',
    middle_name: null,
    notes: null,
    suffix: null,
  },
  {
    email: null,
    first_name: 'Amanda',
    last_name: 'Dockry',
    middle_name: 'Emma',
    notes: null,
    suffix: null,
  },
  {
    email: null,
    first_name: 'Huck',
    last_name: 'Kitten',
    middle_name: null,
    notes: null,
    suffix: null,
  },
  {
    email: null,
    first_name: 'Conor',
    last_name: 'Dockry',
    middle_name: null,
    notes: null,
    suffix: null,
  },
  {
    email: null,
    first_name: 'Bill',
    last_name: 'Brasky',
    middle_name: null,
    notes: null,
    suffix: null,
  },
  {
    email: null,
    first_name: 'Babe',
    last_name: 'Ruth',
    middle_name: null,
    notes: null,
    suffix: null,
  },
  {
    email: null,
    first_name: 'Mitsy',
    last_name: 'Terlecky',
    middle_name: null,
    notes: null,
    suffix: null,
  },
]
